In [1]:
import numpy as np

"""
Numpy is a leanear algebra library for python which many other data related
modules rely on since it provides fundamental data structures, mainly arrays 
(vectors) and matricies, to work with. 
"""

'\nNumpy is a leanear algebra library for python which many other data related\nmodules rely on since it provides fundamental data structures, mainly arrays \n(vectors) and matricies, to work with. \n'

# Arrays

## Creation

### Manual

In [2]:
# Create an array from a list
my_list = [1,2,3]

NumPy_Array = np.array([1, 2, 3])
NumPy_Array = np.array(my_list)

NumPy_Array


array([1, 2, 3])

In [3]:
Python_List = NumPy_Array.tolist() # Method 1
Python_List = list(NumPy_Array)    # Method 2

Python_List

[1, 2, 3]

In [4]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

Numpy_Matrix = np.array(my_matrix)
Numpy_Matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Automatically

In [5]:
# Arange (Array range)
# arr = np.arange(start, stop, step)
# Return evenly spaced values within a given interval. 

NumPy_Arange1 = np.arange(0, 10)
NumPy_Arange1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
NumPy_Arange2 = np.arange(0, 100, 10)
NumPy_Arange2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
NumPy_linspace = np.linspace(0,5,10)
NumPy_linspace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
Rounded_Linspace = np.round(NumPy_linspace,2)
Rounded_Linspace

array([0.  , 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.  ])

In [9]:
# Create an array of zeros
# arr = np.zeros(size)

Zeros_Array = np.zeros(3)
Zeros_Array

array([0., 0., 0.])

In [10]:
Zeros_Matrix = np.zeros((5,5)) # (Rows, Columns)
Zeros_Matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
Ones_Array = np.ones(3)
Ones_Array

array([1., 1., 1.])

In [12]:
Ones_Matrix = np.ones((5,5))
Ones_Matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create an identity matrix
Identity_Matrix = np.eye(5)
Identity_Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
diagonal_matrix = np.diag([1, 2, 3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
Random_Array = np.random.rand(5)
Random_Array

array([0.5985333 , 0.88998106, 0.75641243, 0.79464358, 0.8222882 ])

In [16]:
Random_Matrix = np.random.rand(5,5)
Random_Matrix

array([[0.90821985, 0.94834298, 0.61249831, 0.57991649, 0.14619223],
       [0.69033064, 0.58231313, 0.6980383 , 0.42005828, 0.73811857],
       [0.46152168, 0.51360929, 0.25851226, 0.46747774, 0.28316615],
       [0.26660408, 0.65510458, 0.85060725, 0.98793939, 0.21381641],
       [0.13992851, 0.86261892, 0.05929664, 0.81710131, 0.34717093]])

In [17]:
# Generate random integers
# np.random.randint(low, high, size)

Random100_Array = np.random.randint(1,100, 100)
Random100_Array


array([16, 90, 26, 93, 33, 70, 13, 81, 82, 71, 97, 34, 87, 87, 27, 45,  2,
       78, 22, 65, 91, 60, 77, 36, 21, 63, 30, 64,  2, 51, 20, 97,  1, 95,
       95, 58, 84, 45, 90, 61, 79, 76, 35, 43, 73, 51, 61, 31, 75, 33, 13,
       97, 78, 68, 65, 73, 97, 72, 10, 61, 46, 43, 42, 56, 60, 74, 99, 22,
       70, 63, 30, 80, 22, 16, 28, 36, 90, 56, 85, 98, 49, 97, 78, 60, 48,
       78, 69, 83, 92, 90, 13, 22, 33, 49, 34, 39, 44, 22, 82, 21])

In [18]:
Random100_Matrix = np.random.randint(1,100, (10,10))
Random100_Matrix

array([[11, 30, 44, 31, 46,  6, 85, 24, 74, 16],
       [25, 17,  3, 53, 76,  5, 79, 42, 16, 11],
       [98, 16, 71, 64, 39, 43, 26, 47, 73, 24],
       [77, 58, 64, 54, 56, 75, 77,  2, 33, 73],
       [14, 73, 66, 15, 97,  7,  9, 88, 72, 59],
       [19, 44, 80,  9, 95,  2, 87, 87, 36, 38],
       [17, 43, 78, 75,  2, 87, 39, 89, 76, 25],
       [84, 40, 61, 40, 47, 24, 68, 34, 74, 50],
       [85, 73, 74, 85, 14, 40, 23,  3, 79, 26],
       [81, 48, 43, 29,  9, 12, 21, 50, 50, 17]])

## Attributes

In [19]:
Inspect_Array = np.arange(1, 101)
Inspect_Array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [20]:
# Shape of the array
Inspect_Array.shape

(100,)

In [21]:
Reshaped_Array = Inspect_Array.reshape(10,10)
Reshaped_Array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
# Number of dimensions
print(Inspect_Array.ndim)
print(Reshaped_Array.ndim)


1
2


In [23]:
print(np.argmax(Random100_Array))
print(np.argmin(Random100_Array))


66
32


## Indexing

### Arrays

In [24]:
Array_Selection = np.arange(0,11)
Array_Selection

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
Array_Selection[8]

8

In [26]:
Array_Selection[1:5]

array([1, 2, 3, 4])

In [27]:
Array_Selection[:6] # Up to, but not including 6

array([0, 1, 2, 3, 4, 5])

In [28]:
Array_Selection[5:] # Start at 5 and finish to the end

array([ 5,  6,  7,  8,  9, 10])

### Matricies

In [29]:
OneHundred_Matrix = np.arange(0, 100).reshape(10, 10)
OneHundred_Matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
Grab35 = OneHundred_Matrix[3][5]
Grab35

35

In [31]:
Grab79 = OneHundred_Matrix[7,9]
Grab79

79

In [32]:
Grab20s = OneHundred_Matrix[2]
Grab20s

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
Grab20thru50 = OneHundred_Matrix[2:6]
Grab20thru50

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

## Booleans

In [34]:
OneHundred_Matrix < 33

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [35]:
Getupto55 = OneHundred_Matrix[OneHundred_Matrix<=55]
Getupto55

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

# Manipulation

In [36]:
# Reshaping
arr.reshape(new_shape)

# Transposing
arr.T

# Flattening
arr.flatten()

# Concatenation
np.concatenate((arr1, arr2), axis=0)


NameError: name 'arr' is not defined

In [ ]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [ ]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)